"use client"
import { useRef } from 'react';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import Header from '../../components/Header';
import fetchCustomer from "./fetchCustomer";
import Link from 'next/link';

import createCustomer from './createCustomer';


const industriesOptions = [
    { value: '1', label: '農業，林業' },
    { value: '2', label: '漁業' },
    { value: '3', label: '鉱業，採石業，砂利採取業' },
    { value: '4', label: '建設業' },
    { value: '5', label: '製造業' },
    { value: '6', label: '電気・ガス・熱供給・水道業' },
    { value: '7', label: '情報通信業' },
    { value: '8', label: '運輸業，郵便業' },
    { value: '9', label: '卸売業，小売業' },
    { value: '10', label: '金融業，保険業' },
    { value: '11', label: '不動産業，物品賃貸業' },
    { value: '12', label: '学術研究，専門・技術サービス業' },
    { value: '13', label: '宿泊業，飲食サービス業' },
    { value: '14', label: '生活関連サービス業，娯楽業' },
    { value: '15', label: '教育，学習支援業' },
    { value: '16', label: '医療，福祉' },
    { value: '17', label: '複合サービス事業' },
    { value: '18', label: 'サービス業（他に分類されないもの）' },
    { value: '19', label: '公務（他に分類されるものを除く）' },
    { value: '20', label: '分類不能の産業' },
  ];

  const detailsOptions = {
    1: [
      { value: 1, label: '農業' },
      { value: 2, label: '林業' },
    ],
    2: [
      { value: 3, label: '漁業（水産養殖業を除く）' },
      { value: 4, label: '水産養殖業' },
    ],
    3: [
      { value: 5, label: '鉱業，採石業，砂利採取業' },
    ],
    4: [
      { value: 6, label: '総合工事業' },
      { value: 7, label: '職別工事業(設備工事業を除く)' },
      { value: 8, label: '設備工事業' },
    ],
    5: [
      { value: 9, label: '食料品製造業' },
      { value: 10,label: '飲料・たばこ・飼料製造業' },
      { value: 11,label: '繊維工業' },
      { value: 12,label: '木材・木製品製造業（家具を除く）' },
      { value: 13,label: '家具・装備品製造業' },
      { value: 14,label: 'パルプ・紙・紙加工品製造業' },
      { value: 15,label: '印刷・同関連業' },
      { value: 16,label: '化学工業' },
      { value: 17,label: '石油製品・石炭製品製造業' },
      { value: 18,label: 'プラスチック製品製造業（別掲を除く）' },
      { value: 19,label: 'ゴム製品製造業' },
      { value: 20,label: 'なめし革・同製品・毛皮製造業' },
      { value: 21,label: '窯業・土石製品製造業' },
      { value: 22,label: '鉄鋼業' },
      { value: 23,label: '非鉄金属製造業' },
      { value: 24,label: '金属製品製造業' },
      { value: 25,label: 'はん用機械器具製造業' },
      { value: 26,label: '生産用機械器具製造業' },
      { value: 27,label: '業務用機械器具製造業' },
      { value: 28,label: '電子部品・デバイス・電子回路製造業' },
      { value: 29,label: '電気機械器具製造業' },
      { value: 30,label: '情報通信機械器具製造業' },
      { value: 31,label: '輸送用機械器具製造業' },
      { value: 32,label: 'その他の製造業' },
    ],
    6: [
      { value: 33,label: '電気業' },
      { value: 34,label: 'ガス業' },
      { value: 35,label: '熱供給業' },
      { value: 36,label: '水道業' },
    ],
    7: [
      { value: 37,label: '通信業' },
      { value: 38,label: '放送業' },
      { value: 39,label: '情報サービス業' },
      { value: 40,label: 'インターネット附随サービス業' },
      { value: 41,label: '映像・音声・文字情報制作業' },
    ],
    8: [
      { value: 42,label: '鉄道業' },
      { value: 43,label: '道路旅客運送業' },
      { value: 44,label: '道路貨物運送業' },
      { value: 45,label: '水運業' },
      { value: 46,label: '航空運輸業' },
      { value: 47,label: '倉庫業' },
      { value: 48,label: '運輸に附帯するサービス業' },
      { value: 49,label: '郵便業（信書便事業を含む）' },
    ],
    9: [
      { value: 50,label: '各種商品卸売業' },
      { value: 51,label: '繊維・衣服等卸売業' },
      { value: 52,label: '飲食料品卸売業' },
      { value: 53,label: '建築材料，鉱物・金属材料等卸売業' },
      { value: 54,label: '機械器具卸売業' },
      { value: 55,label: 'その他の卸売業' },
      { value: 56,label: '各種商品小売業' },
      { value: 57,label: '織物・衣服・身の回り品小売業' },
      { value: 58,label: '飲食料品小売業' },
      { value: 59,label: '機械器具小売業' },
      { value: 60,label: 'その他の小売業' },
      { value: 61,label: '無店舗小売業' },
    ],
    10: [
      { value: 62,label: '銀行業' },
      { value: 63,label: '協同組織金融業' },
      { value: 64,label: '貸金業，クレジットカード業等非預金信用機関' },
      { value: 65,label: '金融商品取引業，商品先物取引業' },
      { value: 66,label: '補助的金融業等' },
      { value: 67,label: '保険業（保険媒介代理業，保険サービス業を含む）' },
    ],
    11: [
      { value: 68,label: '不動産取引業' },
      { value: 69,label: '不動産賃貸業・管理業' },
      { value: 70,label: '物品賃貸業' },
    ],
    12: [
      { value: 71,label: '学術・開発研究機関' },
      { value: 72,label: '専門サービス業（他に分類されないもの）' },
      { value: 73,label: '広告業' },
      { value: 74,label: '技術サービス業（他に分類されないもの）' },
    ],
    13: [
      { value: 75,label: '宿泊業' },
      { value: 76,label: '飲食店' },
      { value: 77,label: '持ち帰り・配達飲食サービス業' },
    ],
    14: [
      { value: 78,label: '洗濯・理容・美容・浴場業' },
      { value: 79,label: 'その他の生活関連サービス業' },
      { value: 80,label: '娯楽業' },
    ],
    15: [
      { value: 81,label: '学校教育' },
      { value: 82,label: 'その他の教育，学習支援業' },
    ],
    16: [
      { value: 83,label: '医療業' },
      { value: 84,label: '保健衛生' },
      { value: 85,label: '社会保険・社会福祉・介護事業' },
    ],
    17: [
      { value: 86,label: '郵便局' },
      { value: 87,label: '協同組合（他に分類されないもの）' },
    ],
    18: [
      { value: 88,label: '廃棄物処理業' },
      { value: 89,label: '自動車整備業' },
      { value: 90,label: '機械等修理業（別掲を除く）' },
      { value: 91,label: '職業紹介・労働者派遣業' },
      { value: 92,label: 'その他の事業サービス業' },
      { value: 93,label: '政治・経済・文化団体' },
      { value: 94,label: '宗教' },
      { value: 95,label: 'その他のサービス業' },
      { value: 96,label: '外国公務' },
    ],
    19: [
      { value: 97,label: '国家公務' },
      { value: 98,label: '地方公務' },
    ],
    20: [
      { value: 99,label: '分類不能の産業' },
    ],
  };

  const careersOptions = [
    { value: '1', label: '経営戦略' },
    { value: '2', label: '人事・人材開発' },
    { value: '3', label: '労務管理' },
    { value: '4', label: '企業法務' },
    { value: '5', label: '総務' },
    { value: '6', label: '広報' },
    { value: '7', label: '経理' },
    { value: '8', label: '資金財務（トレジャリー）' },
    { value: '9', label: '経営管理分析（FP&A）' },
    { value: '10', label: '情報システム' },
    { value: '11', label: '営業' },
    { value: '12', label: 'マーケティング' },
    { value: '13', label: '広告' },
    { value: '14', label: '生産管理プランニング' },
    { value: '15', label: '生産管理オペレーション' },
    { value: '16', label: 'ロジスティクス管理' },
    { value: '17', label: 'ロジスティクス・オペレーション' },
    { value: '18', label: '国際経営管理' },
    { value: '19', label: '貿易' },
    { value: '20', label: 'プロジェクト管理' },
    { value: '21', label: '調査・企画管理' },
    { value: '22', label: '意匠・設計管理' },
    { value: '23', label: '製作・施工管理' },
    { value: '24', label: '運営管理' },
    { value: '25', label: '基礎研究' },
    { value: '26', label: '製品開発' },
    { value: '27', label: '店舗従業員教育' },
    { value: '28', label: 'オペレーション管理' },
    { value: '29', label: 'キッチン' },
    { value: '30', label: 'フロアサービス' },
    { value: '31', label: '店舗管理' },
    { value: '32', label: '運営事務' },
    { value: '33', label: 'フロント' },
    { value: '34', label: 'トレーニングジム' },
    { value: '35', label: 'スタジオ' },
    { value: '36', label: 'プール' },
    { value: '37', label: 'メーカー・サービス' },
    { value: '38', label: 'リテール・サービス' },
    { value: '39', label: 'ロジスティクス' },
    { value: '40', label: '販売' },
    { value: '41', label: '販売・加工' },
    { value: '42', label: 'チェッカー' },
    { value: '43', label: 'ストアマネジメント' },
    { value: '44', label: '販売指導' },
    { value: '45', label: 'トレーナー' },
    { value: '46', label: '店舗運営' },
    { value: '47', label: 'スーパーバイザー' },
    { value: '48', label: '仕入れ' },
    { value: '49', label: '営業企画' },
    { value: '50', label: '施工管理' },
    { value: '51', label: '現場管理' },
    { value: '52', label: '施工技能' },
    { value: '53', label: 'ロピーサービス' },
    { value: '54', label: 'コンシェルジュ' },
    { value: '55', label: 'フロントオフィス' },
    { value: '56', label: '客室予約' },
    { value: '57', label: 'ハウスキーピング' },
    { value: '58', label: 'レストランサービス' },
    { value: '59', label: 'ルームサービス' },
    { value: '60', label: 'ソムリエ' },
    { value: '61', label: '仕入管理' },
    { value: '62', label: '宴会サービス' },
    { value: '63', label: '宴会予約・販売管理' },
    { value: '64', label: 'マーチャンダイジング' },
    { value: '65', label: '検反・裁断' },
    { value: '66', label: '縫製' },
    { value: '67', label: '製造管理' },
    { value: '68', label: '店舗運営' },
    { value: '69', label: '店舗管理' },
    { value: '70', label: '受注営業' },
    { value: '71', label: 'コーディネーション' },
    { value: '72', label: '（交渉・調整）' },
    { value: '73', label: 'クライアント管理' },
    { value: '74', label: 'コンテンツ企画立案' },
    { value: '75', label: '設計・制作ディレクション' },
    { value: '76', label: 'サイト分析' },
    { value: '77', label: 'サイト運営' },
    { value: '78', label: 'ウェブデザイン・コンテンツ制作' },
  ];

  const qualificationsLargeOptions = [
    { value: '1', label: 'IT・情報処理' },
    { value: '2', label: 'コンサルタント' },
    { value: '3', label: 'ビジネス' },
    { value: '4', label: '安全・危険物' },
    { value: '5', label: '医療・介護' },
    { value: '6', label: '飲食・食品' },
    { value: '7', label: '運転・整備' },
    { value: '8', label: '運動・コーチ' },
    { value: '9', label: '英語・語学' },
    { value: '10', label: '会計・財務' },
    { value: '11', label: '環境' },
    { value: '12', label: '教育・学術' },
    { value: '13', label: '計算・統計' },
    { value: '14', label: '健康・心理' },
    { value: '15', label: '公務員・採用試験' },
    { value: '16', label: '工業・技能' },
    { value: '17', label: '国際・観光' },
    { value: '18', label: '司法・法律' },
    { value: '19', label: '趣味・知識' },
    { value: '20', label: '生活・暮らし' },
    { value: '21', label: '船舶' },
    { value: '22', label: '操縦・工事' },
    { value: '23', label: '電気・無線' },
    { value: '24', label: '動物' },
    { value: '25', label: '美容・ファッション' },
    { value: '26', label: '不動産・建築・建物' },
  ];

  const qualificationsSmallOptions = {
    1: [
      { value: 1, label: 'ITパスポート' },
      { value: 2, label: '基本情報技術者' },
      { value: 3, label: '応用情報技術者' },
      { value: 4, label: 'システムアーキテクト' },
      { value: 5, label: 'ビジネス統計スペシャリスト' },
      { value: 6, label: '情報処理安全確保支援士' },
      { value: 7, label: 'ITストラテジスト' },
      { value: 8, label: 'システム監査技術者' },
      { value: 9, label: 'ネットワークスペシャリスト' },
      { value: 10, label: 'プロジェクトマネージャ' },
      { value: 11, label: '医療情報技師' },
      { value: 12, label: 'ITサービスマネージャ' },
      { value: 13, label: 'AWS認定' },
      { value: 14, label: 'Webデザイナー検定' },
      { value: 15, label: 'エンベデッドシステムスペシャリスト' },
      { value: 16, label: 'データベーススペシャリスト' },
      { value: 17, label: 'ディジタル技術検定' },
      { value: 18, label: 'マイクロソフト オフィス スペシャリスト' },
      { value: 19, label: '日商PC検定試験' },
      { value: 20, label: 'オラクルマスター' },
      { value: 21, label: 'LPIC' },
      { value: 22, label: 'C言語プログラミング能力認定試験' },
      { value: 23, label: 'E資格（JDLA Deep Learning for ENGINEER）' },
      { value: 24, label: 'CISSP' },
      { value: 25, label: '情報セキュリティマネジメント' },
      { value: 26, label: '情報セキュリティ管理士認定試験' },
      { value: 27, label: '生成ＡＩパスポート試験' },
      { value: 28, label: 'IoTシステム技術検定' },
      { value: 29, label: 'テクニカルコミュニケーション技術検定' },
      { value: 30, label: 'シスコ技術者認定' },
      { value: 31, label: 'IT検証技術者認定試験（IVEC）' },
      { value: 32, label: 'Oracle認定Javaプログラマ（Java SE）' },
      { value: 33, label: 'モバイルシステム技術検定' },
      { value: 34, label: 'Microsoft Azure 認定資格' },
      { value: 35, label: 'RPA技術者検定' },
      { value: 36, label: 'LinuC' },
      { value: 37, label: 'Google Cloud 認定資格' },
      { value: 38, label: 'HTML5プロフェッショナル認定試験' },
      { value: 39, label: 'G検定（ジェネラリスト検定）' },
      { value: 40, label: 'Python3 エンジニア認定基礎試験' },
      { value: 41, label: 'OSS-DB技術者認定試験' },
      { value: 42, label: 'DTP検定' },
      { value: 43, label: 'JSTQB 認定テスト技術者資格' },
      { value: 44, label: 'CompTIA' }, 
      { value: 45, label: 'インターネット実務検定（I検）' }, 
      { value: 46, label: 'コンピュータサービス技能評価試験（CS試験）' }, 
      { value: 47, label: 'ウェブ解析士' }, 
      { value: 48, label: '情報処理技能検定試験' }, 
      { value: 49, label: 'SAP認定コンサルタント資格' }, 
      { value: 50, label: "P検（ICTプロフィシエンシー検定試験）" },
      { value: 51, label: "データサイエンティスト検定 リテラシー..." },
      { value: 52, label: "日商プログラミング検定" },
      { value: 53, label: "MTA（マイクロソフトテクノロジーアソシ..." },
      { value: 54, label: "PHP技術者認定試験" },
      { value: 55, label: "MySQL 認定資格" },
      { value: 56, label: "WEBライティング技能検定" },
      { value: 57, label: "医療情報システム監査人" },
      { value: 58, label: "JP1試験" },
      { value: 59, label: "ITIL Foundation" },
      { value: 60, label: "ITコーディネータ（ITC）" },
      { value: 61, label: ".com Master" },
      { value: 62, label: "モバイルサイト認定資格" },
      { value: 63, label: "CISM（公認情報セキュリティマネージャー）" },
      { value: 64, label: "ICT支援員" },
      { value: 65, label: "DTPエキスパート" },
      { value: 66, label: "アドビ認定プロフェッショナル「Adobe C..." },
      { value: 67, label: "CISA（公認情報システム監査）" },
      { value: 68, label: "iNARTE-EMC" },
      { value: 69, label: "IT導入士" },
      { value: 70, label: "検索技術者検定" },
      { value: 71, label: "プレゼンテーション作成検定試験" },
      { value: 72, label: "Javaプログラミング能力認定試験" },
      { value: 73, label: "Ruby技術者認定試験" },
      { value: 74, label: "マイクロソフト認定トレーナー（MCT）" },
      { value: 75, label: "AI実装検定" },
      { value: 76, label: "情報検定（J検）" },
      { value: 77, label: "IoT検定" },
      { value: 78, label: "ソフトウェア品質技術者" },
      { value: 79, label: "Google アナリティクス個人認定資格（GA..." },
      { value: 80, label: "Google 広告の認定資格" },
      { value: 81, label: "Google Marketing Platform 認定試験" },
      { value: 82, label: "YouTube 認定資格" },
      { value: 83, label: "CGクリエイター検定" },
      { value: 84, label: "IMA検定" },
      { value: 85, label: "画像処理エンジニア検定" },
      { value: 86, label: "ウェブデザイン技能検定" },
      { value: 87, label: "CGエンジニア検定" },
      { value: 88, label: "タイピング技能検定" },
      { value: 89, label: "Webクリエイター能力認定試験" },
      { value: 90, label: "VBAエキスパート" },
      { value: 91, label: "電子ファイリング検定" },
      { value: 92, label: "マルチメディア検定" },
      { value: 93, label: "Yahoo!プロモーション広告 プロフェッシ..." },
      { value: 94, label: "アドビ認定アソシエイト Photoshop" }
    ],
    2: [
      { value: 1, label: "ファイナンシャル・プランニング技能検定" },
      { value: 2, label: "社会保険労務士" },
      { value: 3, label: "貸金業務取扱主任者" },
      { value: 4, label: "紛争解決手続代理業務試験" },
      { value: 5, label: "中小企業診断士" },
      { value: 6, label: "品質マネジメントシステム審査員" },
      { value: 7, label: "消費生活相談員" },
      { value: 8, label: "RCCM" },
      { value: 9, label: "クレジット債権管理士" },
      { value: 10, label: "年金アドバイザー" },
      { value: 11, label: "日本アンダーライティング協会資格試験" },
      { value: 12, label: "外務員資格試験（一種・二種）" },
      { value: 13, label: "ファイナンシャル・プランニング技能検定" },
      { value: 14, label: "損害保険登録鑑定人" },
      { value: 15, label: "テクニカルアナリスト" },
      { value: 16, label: "金融窓口サービス技能士" },
      { value: 17, label: "キャリアコンサルタント試験" },
      { value: 18, label: "CFA" },
      { value: 19, label: "銀行業務検定" },
      { value: 20, label: "JQE資格" },
      { value: 21, label: "消費生活専門相談員" },
      { value: 22, label: "投資診断士" },
      { value: 23, label: "経営士・経営士補" },
      { value: 24, label: "国際公認投資アナリスト CIIA" },
      { value: 25, label: "CIA（公認内部監査人）" },
      { value: 26, label: "知的財産アナリスト" },
      { value: 27, label: "消費生活アドバイザー" },
      { value: 28, label: "企業経営アドバイザー検定" },
      { value: 29, label: "労務管理士" },
      { value: 30, label: "証券アナリスト CMA" },
      { value: 31, label: "DCプランナー" },
      { value: 32, label: "農業経営アドバイザー" },
      { value: 33, label: "プライベートバンカー" },
      { value: 34, label: "公認不正検査士（CFE）" },
      { value: 35, label: "CFP" },
      { value: 36, label: "マネジメント検定" },
      { value: 37, label: "応用地形判読士" },
      { value: 38, label: "雇用環境整備士" },
      { value: 39, label: "損保一般試験" },
      { value: 40, label: "RMO" },
      { value: 41, label: "認定アセットマネージャー国際資格検定" },
      { value: 42, label: "アクチュアリー" },
      { value: 43, label: "保険仲立人試験" },
      { value: 44, label: "アジャスター試験" },
      { value: 45, label: "キャリアコンサルティング技能検定" },
      { value: 46, label: "住宅ローンアドバイザー" },
      { value: 47, label: "印刷営業士・管理印刷営業士" },
      { value: 48, label: "住宅ローン診断士" },
      { value: 49, label: "AFP" }
    ],    
    3: [
      { value: 1, label: "ビジネスマネジャー検定試験" },
      { value: 2, label: "秘書検定" },
      { value: 3, label: "品質管理検定（QC検定）" },
      { value: 4, label: "調達プロフェッショナル認定資格 CPP" },
      { value: 5, label: "電話応対技能検定（もしもし検定）" },
      { value: 6, label: "第一線監督者マネジメント資格 CPF" },
      { value: 7, label: "サービス接遇検定" },
      { value: 8, label: "全商ビジネス文書実務検定" },
      { value: 9, label: "人事総務検定" },
      { value: 10, label: "リテールマーケティング（販売士）検定" },
      { value: 11, label: "給与計算実務能力検定" },
      { value: 12, label: "個人情報保護士" },
      { value: 13, label: "個人情報保護実務検定" },
      { value: 14, label: "ビジネス・キャリア検定" },
      { value: 15, label: "健康経営アドバイザー" },
      { value: 16, label: "文書情報管理士" },
      { value: 17, label: "派遣元責任者" },
      { value: 18, label: "生産技術者マネジメントスキル認定資格" },
      { value: 19, label: "クレジット審査業務能力検定" },
      { value: 20, label: "ビジネス文書検定" },
      { value: 21, label: "認定コンプライアンス・オフィサー" },
      { value: 22, label: "ビジネスコンプライアンス検定" },
      { value: 23, label: "経済学検定試験" },
      { value: 24, label: "交渉アナリスト" },
      { value: 25, label: "商業経済検定" },
      { value: 26, label: "障害者職業生活相談員" },
      { value: 27, label: "接客サービスマナー検定" },
      { value: 28, label: "文書処理能力検定" },
      { value: 29, label: "職業紹介責任者" },
      { value: 30, label: "CSR検定" },
      { value: 31, label: "PRプランナー" },
      { value: 32, label: "リモート実務検定" },
      { value: 33, label: "文字起こし技能テスト" },
      { value: 34, label: "日経TEST" },
      { value: 35, label: "認定ファシリティマネジャー" },
      { value: 36, label: "物流技術管理士" },
      { value: 37, label: "IPO実務検定" },
      { value: 38, label: "実用マナー検定" },
      { value: 39, label: "ビジネス能力検定（B検）ジョブパス" },
      { value: 40, label: "PMP（Project Management Professional）" },
      { value: 41, label: "マイナンバー実務検定" },
      { value: 42, label: "求人広告取扱者" },
      { value: 43, label: "記録情報管理士" },
      { value: 44, label: "社会人常識マナー検定" },
      { value: 45, label: "マーケティング・ビジネス実務検定" },
      { value: 46, label: "ビジネス実務マナー検定" },
      { value: 47, label: "販路コーディネータ" },
      { value: 48, label: "日商マスター" },
      { value: 49, label: "MBA" },
      { value: 50, label: "公文書管理検定" },
      { value: 51, label: "VEリーダー（VEL）" },
      { value: 52, label: "通販エキスパート検定" },
      { value: 53, label: "接客販売技能検定" },
      { value: 54, label: "ファイリング・デザイナー検定" }
    ],
    4: [
      { value: 1, label: "危険物取扱者" },
      { value: 2, label: "火薬類取扱保安責任者" },
      { value: 3, label: "毒物劇物取扱責任者" },
      { value: 4, label: "特定化学物質及び四アルキル鉛等作業主任者" },
      { value: 5, label: "自衛消防技術試験" },
      { value: 6, label: "高圧ガス製造保安責任者" },
      { value: 7, label: "警備業務検定" },
      { value: 8, label: "エックス線作業主任者" },
      { value: 9, label: "高圧ガス販売主任者" },
      { value: 10, label: "高圧ガス移動監視者" },
      { value: 11, label: "河川点検士" },
      { value: 12, label: "予防技術検定" },
      { value: 13, label: "放射線取扱主任者" },
      { value: 14, label: "火薬類製造保安責任者" },
      { value: 15, label: "保安業務員" },
      { value: 16, label: "液化石油ガス設備士" },
      { value: 17, label: "ガス主任技術者" },
      { value: 18, label: "防火設備検査員" },
      { value: 19, label: "特定高圧ガス取扱主任者" },
      { value: 20, label: "石油機器技術管理士" },
      { value: 21, label: "倉庫管理主任者" },
      { value: 22, label: "作業環境測定士" },
      { value: 23, label: "消防設備点検資格者" },
      { value: 24, label: "原子炉主任技術者" },
      { value: 25, label: "消防設備士" },
      { value: 26, label: "発破技士" },
      { value: 27, label: "充てん作業者" },
      { value: 28, label: "機械警備業務管理者" },
      { value: 29, label: "労働安全コンサルタント" },
      { value: 30, label: "防火対象物点検資格者" },
      { value: 31, label: "ガンマ線透過写真撮影作業主任者" },
      { value: 32, label: "防災センター要員" },
      { value: 33, label: "特定建築物調査員" },
      { value: 34, label: "公園管理運営士" },
      { value: 35, label: "安全保障輸出管理実務能力認定試験" },
      { value: 36, label: "はい作業主任者" },
      { value: 37, label: "高気圧業務特別教育" },
      { value: 38, label: "警備員指導教育責任者" },
      { value: 39, label: "安全衛生推進者" },
      { value: 40, label: "採石業務管理者" },
      { value: 41, label: "核燃料取扱主任者" },
      { value: 42, label: "防災士" },
      { value: 43, label: "航空管制官" },
      { value: 44, label: "石綿作業主任者" },
      { value: 45, label: "プレス機械作業主任者" },
      { value: 46, label: "防犯設備士" },
      { value: 47, label: "消防官・消防士" },
      { value: 48, label: "カス機器設置スヘシャリスト（GSS）" },
      { value: 49, label: "防火安全技術者" },
      { value: 50, label: "防火管理者" },
      { value: 51, label: "道路橋点検士" },
      { value: 52, label: "高速道路点検診断資格" },
      { value: 53, label: "安全管理者" },
      { value: 54, label: "廃棄物処理施設作業従事者特別教育" },
      { value: 55, label: "ポンプ施設管理技術者" },
      { value: 56, label: "防犯診断士" },
      { value: 57, label: "有機溶剤作業主任者" },
      { value: 58, label: "核燃料物質等取扱業務従事者" },
      { value: 59, label: "公園施設点検管理士" },
      { value: 60, label: "ガス消費機器設置工事監督者" },
      { value: 61, label: "林業架線作業主任者" },
      { value: 62, label: "タイヤの空気充填作業者" },
      { value: 63, label: "コンクリート破砕器作業主任者" },
      { value: 64, label: "職長・安全衛生責任者教育" },
      { value: 65, label: "水質管理責任者" },
      { value: 66, label: "保安業務監督者" },
      { value: 67, label: "公共施設保守点検技士・管理士" },
      { value: 68, label: "保安係員" },
      { value: 69, label: "防災介助士" },
      { value: 70, label: "酸素欠乏・硫化水素危険作業主任者" },
      { value: 71, label: "ダム管理主任技術者" },
      { value: 72, label: "ダム水路主任技術者" },
      { value: 73, label: "防災管理者" },
      { value: 74, label: "普通第1種圧力容器取扱作業主任者" },
      { value: 75, label: "化学設備関係第一種圧力容器取扱作業主任者" },
      { value: 76, label: "防災管理点検資格者" },
      { value: 77, label: "乾燥設備作業主任者" },
      { value: 78, label: "高圧室内作業主任者" },
      { value: 79, label: "酸素欠乏・硫化水素危険作業者" },
      { value: 80, label: "ダム管理技士" },
      { value: 81, label: "特殊化学設備作業者" },
      { value: 82, label: "エックス線等透過写真撮影者" },
      { value: 83, label: "石綿取扱い作業者特別教育" },
      { value: 84, label: "四アルキル鉛作業者特別教育" },
      { value: 85, label: "特定粉じん作業者" }
    ],
    5: [
      { value: 1, label: "介護福祉士" },
      { value: 2, label: "看護師" },
      { value: 3, label: "臨床検査技師" },
      { value: 4, label: "衛生工学衛生管理者" },
      { value: 5, label: "医師" },
      { value: 6, label: "社会福祉士" },
      { value: 7, label: "助産師" },
      { value: 8, label: "歯科衛生士" },
      { value: 9, label: "薬剤師" },
      { value: 10, label: "介護支援専門員（ケアマネジャー）" },
      { value: 11, label: "診療放射線技師" },
      { value: 12, label: "医学物理士" },
      { value: 13, label: "保健師" },
      { value: 14, label: "赤十字救急法救急員" },
      { value: 15, label: "サービス介助士（ケアフィッター）" },
      { value: 16, label: "理学療法士" },
      { value: 17, label: "医療経営士" },
      { value: 18, label: "歯科技工士" },
      { value: 19, label: "作業療法士" },
      { value: 20, label: "医療事務技能審査試験" },
      { value: 21, label: "高齢者傾聴スペシャリスト" },
      { value: 22, label: "福祉住環境コーディネーター検定試験" },
      { value: 23, label: "第1種滅菌技師・第2種滅菌技士" },
      { value: 24, label: "救急救命士" },
      { value: 25, label: "サービス管理責任者" },
      { value: 26, label: "応急手当普及員" },
      { value: 27, label: "精神保健福祉士" },
      { value: 28, label: "応急手当指導員" },
      { value: 29, label: "認定救急検査技師" },
      { value: 30, label: "歯科医師" },
      { value: 31, label: "認定心電検査技師" },
      { value: 32, label: "登録販売者" },
      { value: 33, label: "心電図検定" },
      { value: 34, label: "診療情報管理士" },
      { value: 35, label: "准看護師" },
      { value: 36, label: "医師国家試験予備試験" },
      { value: 37, label: "細胞検査士" },
      { value: 38, label: "社会福祉主事" },
      { value: 39, label: "児童発達支援管理責任者" },
      { value: 40, label: "視能訓練士" },
      { value: 41, label: "認定看護師" },
      { value: 42, label: "介護職員初任者研修" },
      { value: 43, label: "滅菌管理士" },
      { value: 44, label: "医師事務作業補助技能認定試験" },
      { value: 45, label: "診療報酬請求事務能力認定試験" },
      { value: 46, label: "認知症ライフパートナー" },
      { value: 47, label: "看護助手認定実務者試験" },
      { value: 48, label: "遺伝子分析科学認定士" },
      { value: 49, label: "病院清掃受託責任者" },
      { value: 50, label: "救命講習" },
      { value: 51, label: "第2種ME技術実力検定試験" },
      { value: 52, label: "MR認定試験" },
      { value: 53, label: "認定眼鏡士" },
      { value: 54, label: "言語聴覚士" },
      { value: 55, label: "認定一般検査技師" },
      { value: 56, label: "メディカルケアワーカー（看護助手）" },
      { value: 57, label: "認知症介護指導者" },
      { value: 58, label: "超音波検査士" },
      { value: 59, label: "医療事務検定試験" },
      { value: 60, label: "介護食士" },
      { value: 61, label: "臨床工学技士" },
      { value: 62, label: "薬学検定" },
      { value: 63, label: "専門看護師" },
      { value: 64, label: "歯科助手検定試験" },
      { value: 65, label: "福祉用具専門相談員" },
      { value: 66, label: "レセプト点検業務検定試験" },
      { value: 67, label: "医事コンピュータ技能検定試験" },
      { value: 68, label: "透析技術認定士" },
      { value: 69, label: "調剤事務管理士" },
      { value: 70, label: "介護予防運動指導員" },
      { value: 71, label: "難病看護師" },
      { value: 72, label: "介護口腔ケア推進士" },
      { value: 73, label: "ケアクラーク技能認定試験" },
      { value: 74, label: "介護事務管理士" },
      { value: 75, label: "第1種ME技術実力検定試験" },
      { value: 76, label: "准サービス介助士" },
      { value: 77, label: "電子カルテオペレーション実務能力認定試験" },
      { value: 78, label: "医療機器修理責任技術者" },
      { value: 79, label: "医療情報実務能力検定試験" },
      { value: 80, label: "医療事務技能認定試験" },
      { value: 81, label: "医療秘書技能検定試験" },
      { value: 82, label: "スマート介護士" },
      { value: 83, label: "医療事務管理士" },
      { value: 84, label: "生活指導員（生活支援員・生活相談員）" },
      { value: 85, label: "義肢装具士" },
      { value: 86, label: "患者給食受託責任者" },
      { value: 87, label: "植込み型心臓不整脈デバイス認定士" },
      { value: 88, label: "体外循環技術認定士" },
      { value: 89, label: "認知症介助士検定試験" },
      { value: 90, label: "移動支援従業者（ガイドヘルパー）" },
      { value: 91, label: "歯科医師国家試験予備試験" },
      { value: 92, label: "歯科助手資格" },
      { value: 93, label: "医事オペレータ技能認定試験" }
    ],
    6: [
      { value: 1, label: "調理師" },
      { value: 2, label: "日本酒検定" },
      { value: 3, label: "管理栄養士" },
      { value: 4, label: "専門調理師・調理技能士" },
      { value: 5, label: "食品衛生責任者" },
      { value: 6, label: "製菓衛生師" },
      { value: 7, label: "食品微生物検査技士" },
      { value: 8, label: "パンシェルジュ検定" },
      { value: 9, label: "食品衛生管理者" },
      { value: 10, label: "発酵検定" },
      { value: 11, label: "国際酒師" },
      { value: 12, label: "日本ビール検定" },
      { value: 13, label: "食の検定" },
      { value: 14, label: "菓子検定" },
      { value: 15, label: "食生活アドバイザー検定" },
      { value: 16, label: "サプリメントアドバイザー" },
      { value: 17, label: "日本ラーメン検定" },
      { value: 18, label: "焼酎検定" },
      { value: 19, label: "ソムリエ" },
      { value: 20, label: "農産物検査員" },
      { value: 21, label: "紅茶検定" },
      { value: 22, label: "酒師" },
      { value: 23, label: "ウイスキー検定" },
      { value: 24, label: "食品表示検定" },
      { value: 25, label: "パン製造技能士" },
      { value: 26, label: "スイーツコンシェルジュ" },
      { value: 27, label: "SAKE DIPLOMA（酒ディプロマ）" },
      { value: 28, label: "お米マイスター" },
      { value: 29, label: "北海道フードマイスター検定" },
      { value: 30, label: "チーズプロフェッショナル資格認定" },
      { value: 31, label: "惣菜管理士" },
      { value: 32, label: "ごはんソムリエ" },
      { value: 33, label: "JBAバリスタライセンス" },
      { value: 34, label: "C.P.A.チーズ検定" },
      { value: 35, label: "HACCP主任技術者" },
      { value: 36, label: "食品安全検定" },
      { value: 37, label: "コーヒーインストラクター検定" },
      { value: 38, label: "薬膳コーディネーター" },
      { value: 39, label: "栄養士" },
      { value: 40, label: "飾り巻き寿司技能認定" },
      { value: 41, label: "食鳥処理衛生管理者" },
      { value: 42, label: "チョコレート検定" },
      { value: 43, label: "ごはん検定 めしけん" },
      { value: 44, label: "お好み焼き検定" },
      { value: 45, label: "菓子製造技能士" },
      { value: 46, label: "食育インストラクター" },
      { value: 47, label: "フードスペシャリスト" },
      { value: 48, label: "アスリートフードマイスター" },
      { value: 49, label: "野菜ソムリエ" },
      { value: 50, label: "きのこ検定" },
      { value: 51, label: "きのこマイスター" },
      { value: 52, label: "HACCP普及指導員" },
      { value: 53, label: "豆腐マイスター" },
      { value: 54, label: "健康食品管理士" },
      { value: 55, label: "家庭料理技能検定" },
      { value: 56, label: "フードアナリスト" },
      { value: 57, label: "WSET" },
      { value: 58, label: "フードコーディネーター資格認定試験" },
      { value: 59, label: "絵巻寿司検定" },
      { value: 60, label: "料理検定" },
      { value: 61, label: "HACCPリーダー（食品安全管理者）" },
      { value: 62, label: "ふぐ取扱責任者" },
      { value: 63, label: "ワインエキスパート" },
      { value: 64, label: "食育アドバイザー" },
      { value: 65, label: "スポーツフードアドバイザー" }
    ],
    7: [
      { value: 1, label: "運行管理者" },
      { value: 2, label: "事業用操縦士" },
      { value: 3, label: "自転車安全整備士" },
      { value: 4, label: "自動車整備士" },
      { value: 5, label: "自家用操縦士" },
      { value: 6, label: "指定自動車教習所指導員" },
      { value: 7, label: "建設機械整備技能士" },
      { value: 8, label: "TOP（交通技術資格者）" },
      { value: 9, label: "中古自動車査定士" },
      { value: 10, label: "小型自動車競走選手（オートレーサー）" },
      { value: 11, label: "農業機械士" },
      { value: 12, label: "定期運送用操縦士" },
      { value: 13, label: "安全運転管理者" },
      { value: 14, label: "航空運航整備士" },
      { value: 15, label: "整備管理者" },
      { value: 16, label: "航空整備士" },
      { value: 17, label: "運航管理者" },
      { value: 18, label: "運転免許" },
      { value: 19, label: "航空工場整備士" },
      { value: 20, label: "航空検査技術者" }
    ],
    8: [
      { value: 1, label: "スポーツ医学検定" },
      { value: 2, label: "健康運動指導士" },
      { value: 3, label: "NSCA-CPT" },
      { value: 4, label: "基礎水泳指導員" },
      { value: 5, label: "JATI-ATI" },
      { value: 6, label: "IGFI" },
      { value: 7, label: "スポーツアロマトレーナー" },
      { value: 8, label: "健康運動実践指導者" },
      { value: 9, label: "JAAF公認指導者" },
      { value: 10, label: "CSCS" },
      { value: 11, label: "コーチング資格" },
      { value: 12, label: "NESTA-PFT" },
      { value: 13, label: "JSPO-AT（アスレティックトレーナー）" },
      { value: 14, label: "Cカード（ダイビングライセンス）" },
      { value: 15, label: "スポーツリーダー（スポーツ指導基礎資格）" },
      { value: 16, label: "スポーツプログラマー" }
    ],
    9: [
      { value: 1, label: "実用英語技能検定（英検）" },
      { value: 2, label: "日本語検定（語検）" },
      { value: 3, label: "スペイン語技能検定" },
      { value: 4, label: "日本漢字能力検定（漢検）" },
      { value: 5, label: "英会話検定" },
      { value: 6, label: "HSK（漢語水平考試）" },
      { value: 7, label: "TOEIC Listening & Reading Test" },
      { value: 8, label: "英単語検定" },
      { value: 9, label: "実用フランス語技能検定（仏検）" },
      { value: 10, label: "ハングル能力検定" },
      { value: 11, label: "語彙・読解力検定" },
      { value: 12, label: "韓国語能力試験（TOPIK）" },
      { value: 13, label: "DELF・DALF" },
      { value: 14, label: "技術英語能力検定" },
      { value: 15, label: "ドイツ語技能検定試験" },
      { value: 16, label: "日本医学英語検定試験" },
      { value: 17, label: "日本語能力試験" },
      { value: 18, label: "ブラジル・ポルトガル語検定試験 Celpe-Bras" },
      { value: 19, label: "TOEFL iBT" },
      { value: 20, label: "英語応対能力検定" },
      { value: 21, label: "インドネシア語技能検定" },
      { value: 22, label: "JTA公認 翻訳専門職資格" },
      { value: 23, label: "医療通訳技能認定試験" },
      { value: 24, label: "ロシア語検定試験" },
      { value: 25, label: "BJT ビジネス日本語能力テスト" },
      { value: 26, label: "実用タイ語検定試験" },
      { value: 27, label: "実用日本語検定" },
      { value: 28, label: "実用イタリア語検定" },
      { value: 29, label: "ビジネス通訳検定（TOBIS）" },
      { value: 30, label: "実用ベトナム語技能検定試験（ViLT）" },
      { value: 31, label: "一般通訳検定（TOUI）" },
      { value: 32, label: "日商ビジネス英語検定" },
      { value: 33, label: "国際連合公用語英語検定試験（国連英検）" },
      { value: 34, label: "日本語教育能力検定試験" },
      { value: 35, label: "中国語検定試験" },
      { value: 36, label: "CBS（国際秘書）検定" },
      { value: 37, label: "観光英語検定" }
    ],
    10: [
      { value: 1, label: "建設業経理検定" },
      { value: 2, label: "公認会計士" },
      { value: 3, label: "税理士" },
      { value: 4, label: "日商簿記検定" },
      { value: 5, label: "金融業務能力検定" },
      { value: 6, label: "消費税法能力検定" },
      { value: 7, label: "所得税法能力検定" },
      { value: 8, label: "ビジネス会計検定試験" },
      { value: 9, label: "電子会計実務検定" },
      { value: 10, label: "米国公認会計士（USCPA）" },
      { value: 11, label: "BATIC（国際会計検定）" },
      { value: 12, label: "法人税法能力検定" },
      { value: 13, label: "農業簿記検定" },
      { value: 14, label: "社会福祉法人経営実務検定試験" },
      { value: 15, label: "FASS検定" },
      { value: 16, label: "地方公会計検定" }
    ],
    11: [
      { value: 1, label: "eco検定（環境社会検定試験）" },
      { value: 2, label: "SDGs検定" },
      { value: 3, label: "一般計量士" },
      { value: 4, label: "公害防止管理者" },
      { value: 5, label: "特別管理産業廃棄物管理責任者" },
      { value: 6, label: "排水管清掃作業監督者" },
      { value: 7, label: "浄化槽管理士" },
      { value: 8, label: "下水道管理技術認定試験" },
      { value: 9, label: "臭気判定士" },
      { value: 10, label: "廃棄物処理施設技術管理者" },
      { value: 11, label: "清掃作業監督者" },
      { value: 12, label: "冷媒フロン類取扱技術者" },
      { value: 13, label: "下水道技術検定" },
      { value: 14, label: "土壌医検定" },
      { value: 15, label: "省エネ・脱炭素エキスパート検定" },
      { value: 16, label: "環境計量士（濃度関係/騒音・振動関係）" },
      { value: 17, label: "街路樹剪定士" },
      { value: 18, label: "環境カウンセラー" },
      { value: 19, label: "統括管理者" },
      { value: 20, label: "環境管理士" },
      { value: 21, label: "浄化槽設備士" },
      { value: 22, label: "造園施工管理技士" },
      { value: 23, label: "産業廃棄物適正管理能力検定" },
      { value: 24, label: "ユニバーサルマナー検定" },
      { value: 25, label: "林業普及指導員" },
      { value: 26, label: "環境アセスメント士" },
      { value: 27, label: "樹木医・樹木医補" },
      { value: 28, label: "環境測定分析士" },
      { value: 29, label: "貯水槽清掃作業監督者" },
      { value: 30, label: "ランドスケープアーキテクト（RLA）" },
      { value: 31, label: "土壌汚染調査技術管理者" },
      { value: 32, label: "土壌環境監理士" },
      { value: 33, label: "水道技術管理者" },
      { value: 34, label: "環境騒音・振動測定士" },
      { value: 35, label: "防除作業監督者" },
      { value: 36, label: "港湾海洋調査士" },
      { value: 37, label: "ビオトープ管理士" },
      { value: 38, label: "土壌環境リスク管理者" },
      { value: 39, label: "浄化槽技術管理者" },
      { value: 40, label: "浄化槽検査員" },
      { value: 41, label: "浄化槽清掃技術者" },
      { value: 42, label: "ダクト清掃作業監督者" },
      { value: 43, label: "グリーンアドバイザー" },
      { value: 44, label: "3R・低炭素社会検定" },
      { value: 45, label: "森林インストラクター" }
    ],
    12: [
      { value: 1, label: "保育士" },
      { value: 2, label: "高等学校卒業程度認定試験" },
      { value: 3, label: "教員資格認定試験" },
      { value: 4, label: "司書・司書補" },
      { value: 5, label: "学芸員・学芸員補" },
      { value: 6, label: "生物分類技能検定" },
      { value: 7, label: "実用理科技能検定" },
      { value: 8, label: "バイオインフォマティクス技術者認定試験" },
      { value: 9, label: "国立国会図書館職員（総合職・一般職）" },
      { value: 10, label: "生理人類士" },
      { value: 11, label: "バイオ技術者認定試験" },
      { value: 12, label: "登録日本語教員" },
      { value: 13, label: "学校図書館司書教諭" }
    ],
    13: [
      { value: 1, label: "暗算検定" },
      { value: 2, label: "珠算能力検定（日本商工会議所）" },
      { value: 3, label: "実用数学技能検定" },
      { value: 4, label: "統計検定" },
      { value: 5, label: "電卓計算能力検定" },
      { value: 6, label: "ビジネス数学検定" },
      { value: 7, label: "思考力検定" },
      { value: 8, label: "社会調査士" }
    ],
    14: [
      { value: 1, label: "公認心理師" },
      { value: 2, label: "衛生管理者" },
      { value: 3, label: "こころ検定" },
      { value: 4, label: "柔道整復師" },
      { value: 5, label: "はり師" },
      { value: 6, label: "整体ボディケアセラピスト" },
      { value: 7, label: "メンタルヘルス・マネジメント検定試験" },
      { value: 8, label: "きゅう師" },
      { value: 9, label: "ピンクリボンアドバイザー" },
      { value: 10, label: "臨床心理士" },
      { value: 11, label: "労働衛生コンサルタント" },
      { value: 12, label: "心理相談員" },
      { value: 13, label: "日本健康マスター検定" },
      { value: 14, label: "認定ハラスメント相談員I種試験" },
      { value: 15, label: "心理学検定" },
      { value: 16, label: "発達障害児支援士" },
      { value: 17, label: "産業カウンセラー" },
      { value: 18, label: "臨床発達心理士" },
      { value: 19, label: "音楽健康指導士" },
      { value: 20, label: "学校心理士" },
      { value: 21, label: "音楽療法士" },
      { value: 22, label: "児童福祉司" },
      { value: 23, label: "臨床美術士（クリニカルアーティスト）" },
      { value: 24, label: "健康管理能力検定" },
      { value: 25, label: "JADP認定メンタル心理カウンセラー" },
      { value: 26, label: "シニア産業カウンセラー" },
      { value: 27, label: "あん摩マッサージ指圧師" },
      { value: 28, label: "メンタルケア心理士・心理専門士" },
      { value: 29, label: "認定心理士" },
      { value: 30, label: "スポーツメンタルトレーナー" },
      { value: 31, label: "児童発達支援士" },
      { value: 32, label: "カラーセラピスト" },
      { value: 33, label: "ロルファー（ロルフィング）" },
      { value: 34, label: "マインドフルネススペシャリスト" },
      { value: 35, label: "認知症予防実践指導士" },
      { value: 36, label: "児童指導員" },
      { value: 37, label: "行動心理士" },
      { value: 38, label: "AMJ実践リーダー" }
    ],
    15: [
      { value: 1, label: "自衛隊幹部候補生（陸・海・空）" },
      { value: 2, label: "自衛官候補生（陸・海・空）" },
      { value: 3, label: "警視庁警察官" },
      { value: 4, label: "自衛官 一般曹候補生（陸・海・空）" },
      { value: 5, label: "刑務官" },
      { value: 6, label: "法務省専門職員（人間科学）" },
      { value: 7, label: "国家公務員一般職（社会人）" },
      { value: 8, label: "海上保安大学校学生" },
      { value: 9, label: "航空保安大学校学生" },
      { value: 10, label: "労働基準監督官" },
      { value: 11, label: "入国警備官" },
      { value: 12, label: "海上保安学校学生" },
      { value: 13, label: "国家公務員一般職（大卒程度）" },
      { value: 14, label: "外務省専門職員" },
      { value: 15, label: "国税専門官" },
      { value: 16, label: "皇宮護衛官（高卒程度）" },
      { value: 17, label: "国家公務員総合職（院卒者）" },
      { value: 18, label: "国家公務員総合職（大卒程度）教養区分除く" },
      { value: 19, label: "国会議員政策担当秘書" },
      { value: 20, label: "防衛省専門職員" },
      { value: 21, label: "食品衛生監視員" },
      { value: 22, label: "地方公務員" },
      { value: 23, label: "海上保安官" },
      { value: 24, label: "国家公務員総合職（院卒者）法務区分" },
      { value: 25, label: "衆議院事務局職員 一般職（大卒程度）" },
      { value: 26, label: "衆議院事務局職員 総合職（大卒程度）" },
      { value: 27, label: "衆議院事務局職員 衛視" },
      { value: 28, label: "参議院事務局職員 総合職（大卒程度）" },
      { value: 29, label: "皇宮護衛官（大卒程度）" },
      { value: 30, label: "国家公務員総合職（大卒程度）教養区分" },
      { value: 31, label: "財務専門官" },
      { value: 32, label: "衆議院事務局職員 一般職（高卒程度）" },
      { value: 33, label: "参議院法制局職員総合職" },
      { value: 34, label: "税務職員" },
      { value: 35, label: "参議院事務局職員 総合職［技術］（大卒..." },
      { value: 36, label: "参議院事務局職員 衛視（高卒程度）" },
      { value: 37, label: "気象大学校学生" },
      { value: 38, label: "海上保安学校学生（特別）" },
      { value: 39, label: "国家公務員一般職（高卒者）" },
      { value: 40, label: "参議院事務局職員 一般職（高卒程度）" },
      { value: 41, label: "衆議院法制局職員総合職" },
      { value: 42, label: "参議院事務局職員 一般職［技術］（高卒..." }
    ],
    16: [
      { value: 1, label: "機械保全技能士" },
      { value: 2, label: "JIS品質管理責任者" },
      { value: 3, label: "自主保全士" },
      { value: 4, label: "機械・プラント製図技能士" },
      { value: 5, label: "計装士" },
      { value: 6, label: "生産マイスター" },
      { value: 7, label: "ボイラー技士" },
      { value: 8, label: "溶接管理技術者" },
      { value: 9, label: "非破壊試験技術者資格試験" },
      { value: 10, label: "潜水士" },
      { value: 11, label: "技術士・技術士補" },
      { value: 12, label: "ビルクリーニング技能士" },
      { value: 13, label: "ボイラー溶接士（普通・特別）" },
      { value: 14, label: "ガス溶接作業主任者" },
      { value: 15, label: "小規模ボイラー取扱者" },
      { value: 16, label: "舗装施工管理技術者" },
      { value: 17, label: "産業洗浄技能士" },
      { value: 18, label: "農業土木技術管理士" },
      { value: 19, label: "セーフティアセッサ" },
      { value: 20, label: "エネルギー管理士" },
      { value: 21, label: "3Dプリンター活用技術検定試験" },
      { value: 22, label: "電子顕微鏡技術認定試験" },
      { value: 23, label: "機械加工技能士" },
      { value: 24, label: "昇降機等検査員" },
      { value: 25, label: "水道（浄水・管路）施設管理技士" },
      { value: 26, label: "計算力学技術者" },
      { value: 27, label: "生産士" },
      { value: 28, label: "3次元CAD利用技術者試験" },
      { value: 29, label: "眼鏡作製技能士" },
      { value: 30, label: "地質調査技士" },
      { value: 31, label: "舗装診断士" },
      { value: 32, label: "自家用発電設備専門技術者" },
      { value: 33, label: "巻締主任技術者" },
      { value: 34, label: "建築CAD検定試験" },
      { value: 35, label: "MUD教育検定" },
      { value: 36, label: "ボイラー整備士" },
      { value: 37, label: "ボイラー・タービン主任技術者" },
      { value: 38, label: "認定補聴器技能者" },
      { value: 39, label: "塗装技能士" },
      { value: 40, label: "化学分析技能士" },
      { value: 41, label: "包装管理士" },
      { value: 42, label: "半導体技術者検定" },
      { value: 43, label: "機械設計技術者" },
      { value: 44, label: "さく井技能士" },
      { value: 45, label: "認定人間工学専門家" },
      { value: 46, label: "太陽光発電メンテナンス技士資格" },
      { value: 47, label: "洗浄技術検定" },
      { value: 48, label: "化学工学技士" },
      { value: 49, label: "CADトレース技能審査" },
      { value: 50, label: "林業技士" },
      { value: 51, label: "エネルギー診断プロフェッショナル" },
      { value: 52, label: "アーク溶接作業者" },
      { value: 53, label: "検査分析士" },
      { value: 54, label: "研削といし取替試運転作業者" },
      { value: 55, label: "2次元CAD利用技術者試験" },
      { value: 56, label: "プレス金型取替作業者" },
      { value: 57, label: "産業用ロボットの特別教育" },
      { value: 58, label: "速記技能検定" },
      { value: 59, label: "ガス溶接技能講習" },
      { value: 60, label: "とび技能士" },
      { value: 61, label: "鉛作業主任者" },
      { value: 62, label: "信頼性技術者" },
      { value: 63, label: "ピアノ調律技能士" },
      { value: 64, label: "サウンドレコーディング技術認定試験" },
      { value: 65, label: "ボイラー据付作業指揮者" }
    ],
    17: [
      { value: 1, label: "国内旅行業務取扱管理者" },
      { value: 2, label: "総合旅行業務取扱管理者" },
      { value: 3, label: "通関士" },
      { value: 4, label: "貿易実務検定" },
      { value: 5, label: "全国通訳案内士" },
      { value: 6, label: "旅行地理検定" },
      { value: 7, label: "JPO派遣制度" },
      { value: 8, label: "IATA DIPLOMA（IATA ディプロマ）" },
      { value: 9, label: "旅程管理主任者（ツアーコンダクター）" },
      { value: 10, label: "カジノディーラー資格認定試験" },
      { value: 11, label: "北海道観光マスター検定" },
      { value: 12, label: "ホテル・マネジメント技能検定" },
      { value: 13, label: "AIBA認定貿易アドバイザー試験" }
    ],
    18: [
      { value: 1, label: "行政書士" },
      { value: 2, label: "弁理士" },
      { value: 3, label: "司法試験" },
      { value: 4, label: "司法書士" },
      { value: 5, label: "ビジネス実務法務検定試験" },
      { value: 6, label: "海事代理士" },
      { value: 7, label: "法学検定試験" },
      { value: 8, label: "裁判所職員一般職（裁判所事務官）" },
      { value: 9, label: "知的財産管理技能検定" },
      { value: 10, label: "裁判所職員総合職（裁判所事務官）" },
      { value: 11, label: "裁判所職員総合職（家庭裁判所調査官補）" },
      { value: 12, label: "執行官" },
      { value: 13, label: "ビジネス著作権検定" },
      { value: 14, label: "司法試験予備試験" },
      { value: 15, label: "特定行政書士" },
      { value: 16, label: "景品表示法務検定" },
      { value: 17, label: "簡裁訴訟代理等能力認定考査" },
      { value: 18, label: "特定侵害訴訟代理業務試験" }
    ],
    19: [
      { value: 1, label: "名探偵コナン検定" },
      { value: 2, label: "すみっコぐらし検定" },
      { value: 3, label: "スパイス&ハーブ検定" },
      { value: 4, label: "茶道文化検定" },
      { value: 5, label: "日本さかな検定（ととけん）" },
      { value: 6, label: "ねこ検定" },
      { value: 7, label: "天文宇宙検定" },
      { value: 8, label: "旅客機・エアライン検定" },
      { value: 9, label: "神社検定" },
      { value: 10, label: "国際知識検定" },
      { value: 11, label: "世界遺産検定" },
      { value: 12, label: "歴史能力検定（歴検）" },
      { value: 13, label: "江戸文化歴史検定" },
      { value: 14, label: "日光検定" },
      { value: 15, label: "日本城郭検定" },
      { value: 16, label: "温泉ソムリエ" },
      { value: 17, label: "メディカルハーブ検定" },
      { value: 18, label: "知識検定" },
      { value: 19, label: "航空検定" },
      { value: 20, label: "ことわざ検定（こと検）" },
      { value: 21, label: "なにわなんでも大阪検定" },
      { value: 22, label: "鎌倉検定" },
      { value: 23, label: "夜景観光士検定" },
      { value: 24, label: "古民家鑑定士" },
      { value: 25, label: "リラックマ検定" },
      { value: 26, label: "東京シティガイド検定" },
      { value: 27, label: "星空宇宙天文検定" },
      { value: 28, label: "金沢検定" },
      { value: 29, label: "地図地理検定" },
      { value: 30, label: "文具知識能力検定" },
      { value: 31, label: "ドローン検定（無人航空従事者試験）" },
      { value: 32, label: "京都・観光文化検定試験" },
      { value: 33, label: "謎解き能力検定" },
      { value: 34, label: "ニュース時事能力検定（N検）" },
      { value: 35, label: "おさかなマイスター・おさかなマイスターコース" },
      { value: 36, label: "ブッシュクラフトアドバイザー" },
      { value: 37, label: "美術検定" },
      { value: 38, label: "バーベキュー検定" },
      { value: 39, label: "DSCO認定クリスタルデコレーション資格" },
      { value: 40, label: "数秘術鑑定士" },
      { value: 41, label: "国宝検定" },
      { value: 42, label: "ハーブ＆ライフ検定" },
      { value: 43, label: "新選組検定" }
    ],
    20: [
      { value: 1, label: "駐車監視員" },
      { value: 2, label: "全国手話検定試験" },
      { value: 3, label: "掃除能力検定" },
      { value: 4, label: "保護司" },
      { value: 5, label: "要約筆記者" },
      { value: 6, label: "普及指導員" },
      { value: 7, label: "ダイエット検定" },
      { value: 8, label: "日本農業技術検定" },
      { value: 9, label: "色彩検定" },
      { value: 10, label: "日本農業検定" },
      { value: 11, label: "ビジネス点字検定" },
      { value: 12, label: "毛筆書写技能検定" },
      { value: 13, label: "刈払機取扱作業者" },
      { value: 14, label: "カラーコーディネーター検定試験" },
      { value: 15, label: "神職資格" },
      { value: 16, label: "家電製品アドバイザー" },
      { value: 17, label: "チャイルドマインダー" },
      { value: 18, label: "気象予報士" },
      { value: 19, label: "手話技能検定" },
      { value: 20, label: "ナマハゲ伝導士" },
      { value: 21, label: "文章読解・作成能力検定" },
      { value: 22, label: "話しことばとコミュニケーション検定" },
      { value: 23, label: "DJI CAMP（スペシャリスト）" },
      { value: 24, label: "芝草管理技術者" },
      { value: 25, label: "お客様対応専門員（CAP）" },
      { value: 26, label: "照明士、照明コンサルタント" },
      { value: 27, label: "相続診断士" },
      { value: 28, label: "DIYアドバイザー" },
      { value: 29, label: "インテリアコーディネーター" },
      { value: 30, label: "クリーニング師" },
      { value: 31, label: "日本調香技術師検定" },
      { value: 32, label: "テープ起こし技術者 資格検定試験" },
      { value: 33, label: "点字技能師" },
      { value: 34, label: "スーパーマーケット検定" },
      { value: 35, label: "硬筆書写技能検定" },
      { value: 36, label: "フォトマスター検定" },
      { value: 37, label: "終活アドバイザー" },
      { value: 38, label: "水産業普及指導員" },
      { value: 39, label: "官能評価士" },
      { value: 40, label: "年金検定" },
      { value: 41, label: "マナー検定" },
      { value: 42, label: "葬祭ディレクター" },
      { value: 43, label: "食育実践プランナー" },
      { value: 44, label: "ベビーシッター資格認定試験" },
      { value: 45, label: "敬語力検定" },
      { value: 46, label: "色彩活用パーソナルカラー検定" },
      { value: 47, label: "校正技能検定" },
      { value: 48, label: "フラワーデコレーター" },
      { value: 49, label: "パーソナルカラリスト検定" },
      { value: 50, label: "声優能力検定" },
      { value: 51, label: "賞状技法士" },
      { value: 52, label: "漢方養生指導士" },
      { value: 53, label: "職業訓練指導員" },
      { value: 54, label: "遺品整理士" },
      { value: 55, label: "感染対策アドバイザー検定" },
      { value: 56, label: "社会教育主事・社会教育主事補" },
      { value: 57, label: "インテリアプランナー" },
      { value: 58, label: "日本語ワープロ検定試験" },
      { value: 59, label: "手話通訳士" },
      { value: 60, label: "キッチンスペシャリスト" },
      { value: 61, label: "温活アドバイザー" },
      { value: 62, label: "終活カウンセラー" },
      { value: 63, label: "ベビーマッサージインストラクター" },
      { value: 64, label: "生前整理診断士" },
      { value: 65, label: "スマートマスター" },
      { value: 66, label: "ベビーシッター技能認定" },
      { value: 67, label: "フラワーデザイナー資格検定試験" },
      { value: 68, label: "ブライダルプランナー検定" },
      { value: 69, label: "JUIDAドローン資格" },
      { value: 70, label: "箸検定" },
      { value: 71, label: "整理収納アドバイザー" }
    ],
    21: [
      { value: 1, label: "海技士" },
      { value: 2, label: "小型船舶操縦士" },
      { value: 3, label: "特定操縦免許" },
      { value: 4, label: "船舶料理士" },
      { value: 5, label: "水先人" },
      { value: 6, label: "油濁防止管理者" },
      { value: 7, label: "船舶に乗り組む衛生管理者" },
      { value: 8, label: "救命艇手" },
      { value: 9, label: "遊漁船業務主任者" },
      { value: 10, label: "限定救命艇手" },
      { value: 11, label: "船の文化検定（ふね検）" },
      { value: 12, label: "船内荷役作業主任者" }
    ],
    22: [
      { value: 1, label: "無人航空機操縦者技能証明" },
      { value: 2, label: "1級土木施工管理技士" },
      { value: 3, label: "2級建設機械施工管理技士" },
      { value: 4, label: "移動式クレーン運転士" },
      { value: 5, label: "クレーン・デリック運転士" },
      { value: 6, label: "玉掛技能者" },
      { value: 7, label: "2級土木施工管理技士" },
      { value: 8, label: "コンクリート技士・主任技師" },
      { value: 9, label: "解体工事施工技士" },
      { value: 10, label: "フォークリフト運転技能者" },
      { value: 11, label: "砂利採取業務主任者" },
      { value: 12, label: "給水装置工事主任技術者" },
      { value: 13, label: "ショベルローダー等運転技能者" },
      { value: 14, label: "1級建設機械施工管理技士" },
      { value: 15, label: "のり面施工管理技術者" },
      { value: 16, label: "簡易内管施工士" },
      { value: 17, label: "排水設備工事責任技術者" },
      { value: 18, label: "チェーンソーによる伐木等特別教育" },
      { value: 19, label: "コンクリート診断士" },
      { value: 20, label: "コンクリート橋架設等作業主任者" },
      { value: 21, label: "ジャッキ式つり上げ機械運転者" },
      { value: 22, label: "不整地運搬車運転者" },
      { value: 23, label: "軌道装置動力車運転者" },
      { value: 24, label: "木材加工用機械作業主任者" },
      { value: 25, label: "車両系建設機械（整地・運搬・積込み用）運転者" },
      { value: 26, label: "ゴンドラ操作者" },
      { value: 27, label: "河川維持管理技術者" },
      { value: 28, label: "採石のための掘削作業主任者" },
      { value: 29, label: "地すべり防止工事士" },
      { value: 30, label: "車両系建設機械（基礎工事用）運転者" },
      { value: 31, label: "コンクリート構造診断士" },
      { value: 32, label: "床上操作式クレーン運転技能講習" },
      { value: 33, label: "地山の掘削及び土止め支保工作業主任者" },
      { value: 34, label: "揚貨装置運転士" },
      { value: 35, label: "ドローン操縦士（ドローン教習所）" },
      { value: 36, label: "高所作業車運転特別教育" },
      { value: 37, label: "巻上げ機運転者" },
      { value: 38, label: "小型移動式クレーン運転技能講習" },
      { value: 39, label: "建設用リフト運転士" },
      { value: 40, label: "車両系建設機械（コンクリート打設用）運転者" },
      { value: 41, label: "機械集材装置運転者" },
      { value: 42, label: "ずい道内作業者特別教育" },
      { value: 43, label: "ロープ高所作業特別教育" },
      { value: 44, label: "フルハーネス型墜落制止用器具特別教育" },
      { value: 45, label: "プレストレストコンクリート技士" },
      { value: 46, label: "高所作業車運転技能講習" },
      { value: 47, label: "鋼橋架設等作業主任者" },
      { value: 48, label: "ずい道等の覆工作業主任者" },
      { value: 49, label: "ずい道等の掘削等作業主任者" },
      { value: 50, label: "ボーリングマシン運転者" },
      { value: 51, label: "車両系建設機械（解体用）運転者" },
      { value: 52, label: "車両系建設機械（締固め用） 運転者" },
      { value: 53, label: "車両系建設機械（基礎工事用）の作業装置の運転者" },
      { value: 54, label: "車両系木材伐出機械運転者" }
    ],
    23: [
      { value: 1, label: "陸上特殊無線技士" },
      { value: 2, label: "アマチュア無線技士（第一級）" },
      { value: 3, label: "アマチュア無線技士（第二級）" },
      { value: 4, label: "第二種電気工事士" },
      { value: 5, label: "航空特殊無線技士" },
      { value: 6, label: "陸上無線技術士" },
      { value: 7, label: "航空無線通信士" },
      { value: 8, label: "電気通信主任技術者" },
      { value: 9, label: "アマチュア無線技士（第三級）" },
      { value: 10, label: "アマチュア無線技士（第四級）" },
      { value: 11, label: "工事担任者" },
      { value: 12, label: "総合無線通信士" },
      { value: 13, label: "海上特殊無線技士" },
      { value: 14, label: "第一種電気工事士" },
      { value: 15, label: "2級電気工事施工管理技士" },
      { value: 16, label: "第三種電気主任技術者" },
      { value: 17, label: "1級電気工事施工管理技士" },
      { value: 18, label: "配電制御システム検査技士" },
      { value: 19, label: "CATV技術者" },
      { value: 20, label: "特種電気工事資格者" },
      { value: 21, label: "情報配線施工技能士" },
      { value: 22, label: "蓄電池設備整備資格者" },
      { value: 23, label: "第一種電気主任技術者" },
      { value: 24, label: "認定電気工事従事者" },
      { value: 25, label: "第二種電気主任技術者" },
      { value: 26, label: "高圧ケーブル工事技術認定講習" },
      { value: 27, label: "低圧電気取扱者" },
      { value: 28, label: "海上無線通信士" },
      { value: 29, label: "高圧・特別高圧電気取扱者" }
    ],
    24: [
      { value: 1, label: "愛玩動物飼養管理士" },
      { value: 2, label: "動物介護士" },
      { value: 3, label: "ペットケアアドバイザー" },
      { value: 4, label: "狩猟免許" },
      { value: 5, label: "家畜人工授精師" },
      { value: 6, label: "獣医師" },
      { value: 7, label: "動物検定" },
      { value: 8, label: "家庭動物管理士" },
      { value: 9, label: "動物看護師" },
      { value: 10, label: "トリマー" },
      { value: 11, label: "実験動物技術者試験" },
      { value: 12, label: "愛玩動物看護師" },
      { value: 13, label: "装蹄師" },
      { value: 14, label: "ペット栄養管理士" },
      { value: 15, label: "認定ペットシッター" },
      { value: 16, label: "家庭犬しつけインストラクター" },
      { value: 17, label: "初生ひな鑑別師" },
      { value: 18, label: "家畜商" },
      { value: 19, label: "愛犬飼育管理士" },
      { value: 20, label: "ペットロス・ハートケアカウンセラー" },
      { value: 21, label: "アニマル・ペットロス療法士" },
      { value: 22, label: "獣医師国家試験予備試験" },
      { value: 23, label: "飼料製造管理者" }
    ],
    25: [
      { value: 1, label: "IBF国際メイクアップアーティスト認定試験" },
      { value: 2, label: "美容師" },
      { value: 3, label: "理容師" },
      { value: 4, label: "メイクセラピー検定" },
      { value: 5, label: "ジュエリーコーディネーター検定試験" },
      { value: 6, label: "アロマテラピー検定" },
      { value: 7, label: "きもの文化検定" },
      { value: 8, label: "ネイリスト技能検定試験" },
      { value: 9, label: "化粧品成分検定" },
      { value: 10, label: "CIDESCOディプロマ" },
      { value: 11, label: "ファッション販売能力検定" },
      { value: 12, label: "服飾士" },
      { value: 13, label: "美容薬学検定" },
      { value: 14, label: "TES 繊維製品品質管理士" },
      { value: 15, label: "スキンケアアドバイザー" },
      { value: 16, label: "日本化粧品検定" },
      { value: 17, label: "アロマテラピーアドバイザー" },
      { value: 18, label: "アロマテラピーインストラクター" },
      { value: 19, label: "CIDESCO衛生管理資格" },
      { value: 20, label: "ファッションビジネス能力検定" },
      { value: 21, label: "アロマセラピスト" },
      { value: 22, label: "パターンメーキング技術検定" }
    ],
    26: [
      { value: 1, label: "宅地建物取引士" },
      { value: 2, label: "管理業務主任者" },
      { value: 3, label: "構造計算適合判定資格者検定" },
      { value: 4, label: "測量士・測量士補" },
      { value: 5, label: "1級電気通信工事施工管理技術士" },
      { value: 6, label: "マンション管理士" },
      { value: 7, label: "建設機械レンタル管理士" },
      { value: 8, label: "2級建築施工管理技士" },
      { value: 9, label: "二級建築士" },
      { value: 10, label: "不動産鑑定士" },
      { value: 11, label: "建築物環境衛生管理技術者" },
      { value: 12, label: "土地改良換地士" },
      { value: 13, label: "補償業務管理士" },
      { value: 14, label: "土地区画整理士技術検定" },
      { value: 15, label: "建築設備士" },
      { value: 16, label: "土地活用プランナー" },
      { value: 17, label: "競売不動産取扱主任者" },
      { value: 18, label: "一級建築士" },
      { value: 19, label: "1級管工事施工管理技士" },
      { value: 20, label: "建築鉄骨検査技術者" },
      { value: 21, label: "賃貸不動産経営管理士" },
      { value: 22, label: "マンション管理員検定" },
      { value: 23, label: "不動産証券化協会認定マスター" },
      { value: 24, label: "敷金診断士" },
      { value: 25, label: "赤外線建物診断技能師" },
      { value: 26, label: "土地家屋調査士" },
      { value: 27, label: "木造建築士" },
      { value: 28, label: "2級管工事施工管理技士" },
      { value: 29, label: "配管技能士" },
      { value: 30, label: "建築設備検査員" },
      { value: 31, label: "空気環境測定実施者" },
      { value: 32, label: "地盤品質判定士" },
      { value: 33, label: "空き家管理士" },
      { value: 34, label: "木造建築物の組立て等作業主任者" },
      { value: 35, label: "建築積算士" },
      { value: 36, label: "ビル設備管理技能士" },
      { value: 37, label: "建築物等の鉄骨の組立て等作業主任者" },
      { value: 38, label: "コンストラクション･マネジャー" },
      { value: 39, label: "宅建マイスター" },
      { value: 40, label: "外壁診断士" },
      { value: 41, label: "不動産コンサルティング技能試験" },
      { value: 42, label: "ホームインスペクター（住宅診断士）" },
      { value: 43, label: "土地改良補償士" },
      { value: 44, label: "鉄筋施工技能士" },
      { value: 45, label: "土木鋼構造診断士" },
      { value: 46, label: "空調給排水管理監督者" },
      { value: 47, label: "2級電気通信工事施工管理技術士" },
      { value: 48, label: "登録実務講習" },
      { value: 49, label: "免震建物点検技術者" },
      { value: 50, label: "ビル経営管理士" },
      { value: 51, label: "インフラ調査士" },
      { value: 52, label: "土地改良補償業務管理者等" },
      { value: 53, label: "建築仕上診断技術者" },
      { value: 54, label: "被災宅地危険度判定士" },
      { value: 55, label: "不動産キャリアパーソン" },
      { value: 56, label: "任意売却取扱主任者" },
      { value: 57, label: "屋外広告士" },
      { value: 58, label: "建築基準適合判定資格者" },
      { value: 59, label: "PC工法施工管理技術者" },
      { value: 60, label: "建築コスト管理士" },
      { value: 61, label: "エクステリアプランナー" },
      { value: 62, label: "管理建築士" },
      { value: 63, label: "配筋探査技術者" },
      { value: 64, label: "ブロック塀診断士" },
      { value: 65, label: "1級建築施工管理技士" },
      { value: 66, label: "型枠支保工の組立て等作業主任者" },
      { value: 67, label: "足場の組立て等作業主任者" },
      { value: 68, label: "不動産実務検定" },
      { value: 69, label: "構造物診断士" },
      { value: 70, label: "再開発プランナー" },
      { value: 71, label: "設備士資格検定試験" },
      { value: 72, label: "免震部建築施工管理技術者" },
      { value: 73, label: "Space Designer検定試験" },
      { value: 74, label: "天井耐震診断士" },
      { value: 75, label: "商業施設士" },
      { value: 76, label: "住宅地盤技術者認定資格（住宅地盤技士）" },
      { value: 77, label: "地盤検査技士" },
      { value: 78, label: "CFT造施工管理技術者" },
      { value: 79, label: "コンクリート造の工作物の解体等作業主任者" },
      { value: 80, label: "シックハウス診断士" },
      { value: 81, label: "不動産流通実務検定（スコア）" },
      { value: 82, label: "足場の組立て等作業従事者特別教育" }
    ],
  };

export default function CreatePage() {
    const formRef = useRef();
    const router = useRouter();

    const handleSubmit = async (event) => {
        event.preventDefault();
        const formData = new FormData(formRef.current);
        await createCustomer(formData);
        router.push(`./create/confirm?customer_id=${formData.get("customer_id")}`);
    };

    const [selectedIndustry_1, setSelectedIndustry_1] = useState('');
    const [selectedDetail_1, setSelectedDetail_1] = useState('');
    const [selectedIndustry_2, setSelectedIndustry_2] = useState('');
    const [selectedDetail_2, setSelectedDetail_2] = useState('');
    const [selectedCareer_1, setSelectedCareer_1] = useState('');
    const [selectedCareer_2, setSelectedCareer_2] = useState('');
    const [selectedQualificationLarge_1, setSelectedQualificationLarge_1] = useState('');
    const [selectedQualificationLarge_2, setSelectedQualificationLarge_2] = useState('');
    const [selectedQualificationSmall_1, setSelectedQualificationSmall_1] = useState('');
    const [selectedQualificationSmall_2, setSelectedQualificationSmall_2] = useState('');
      
    const handleIndustryChange_1 = (event) => {
        const selectedIndustry = event.target.value;
        setSelectedIndustry_1(selectedIndustry);
        setSelectedDetail_1(''); // 業種が変わったら業務詳細をリセット
    };
      
    const handleDetailChange_1 = (event) => {
        const selectedDetail = event.target.value;
        setSelectedDetail_1(selectedDetail);
    };
    
    const handleIndustryChange_2 = (event) => {
        const selectedIndustry = event.target.value;
        setSelectedIndustry_2(selectedIndustry);
        setSelectedDetail_2(''); // 業種が変わったら業務詳細をリセット
    };
      
    const handleDetailChange_2 = (event) => {
        const selectedDetail = event.target.value;
        setSelectedDetail_2(selectedDetail);
    };
    
   const handleCareerChange_1 = (event) => {
        const selectedCareer = event.target.value;
        setSelectedCareer_1(selectedCareer);
    };
    
    const handleCareerChange_2 = (event) => {
        const selectedCareer = event.target.value;
        setSelectedCareer_2(selectedCareer);
    };

    const handleQualificationLargeChange_1 = (event) => {
      const selectedQualificationLarge = event.target.value;
      setSelectedQualificationLarge_1(selectedQualificationLarge);
      setSelectedQualificationSmall_1(''); // 業種が変わったら業務詳細をリセット
    };
    
    const handleQualificationSmallChange_1 = (event) => {
        const selectedQualificationSmall = event.target.value;
        setSelectedQualificationSmall_1(selectedQualificationSmall);
    };

    const handleQualificationLargeChange_2 = (event) => {
      const selectedQualificationLarge = event.target.value;
      setSelectedQualificationLarge_2(selectedQualificationLarge);
      setSelectedQualificationSmall_2(''); // 業種が変わったら業務詳細をリセット
    };
    
    const handleQualificationSmallChange_2 = (event) => {
        const selectedQualificationSmall = event.target.value;
        setSelectedQualificationSmall_2(selectedQualificationSmall);
    };

    return (
        <>
            <Header />
            <div className='container'>
              <h2 className='flex font-bold' style={{fontSize:"20px"}}>ユーザー情報登録</h2>
              <div className="card bordered bg-white border-blue-200 border-2 max-w-md m-4">
                  <div className="m-4 card bordered bg-blue-200 duration-200 hover:border-r-red">
                    <form ref={formRef} onSubmit={handleSubmit}>
                          <div className="card-body">
                              <h2 className="card-title">
                                  <p><input type="text" name="customer_name" placeholder="桃太郎" className="input input-bordered" /></p>
                              </h2>
                              <p>Customer ID:<input type="text" name="customer_id" placeholder="C030" className="input input-bordered" /></p>
                              <p>Age:<input type="number" name="age" placeholder="30" className="input input-bordered" /></p>
                              <p>Gender:<input type="text" name="gender" placeholder="女" className="input input-bordered" /></p>
                              <p>Industry_1:
                                  <select
                                      className="select select-bordered w-full max-w-xs"
                                      onChange={handleIndustryChange_1}
                                      value={selectedIndustry_1}
                                  >
                                  <option disabled value="">産業を選択してください</option>
                                  {industriesOptions.map((option) => (
                                      <option key={option.value} value={option.value}>{option.label}</option>
                                  ))}
                                  </select>
                              </p>
                              <p>detail_1:
                                  <select
                                      className="select select-bordered w-full max-w-xs"
                                      onChange={handleDetailChange_1}
                                      value={selectedDetail_1}
                                      name='career_l1'
                                  >
                                  <option disabled value="">業務詳細を選択してください</option>
                                  {detailsOptions[selectedIndustry_1]?.map((option) => (
                                      <option key={option.value} value={option.label}>{option.label}</option>
                                  ))}
                                  </select>
                              </p>
                              <p>career_1:
                                  <select
                                      className="select select-bordered w-full max-w-xs"
                                      onChange={handleCareerChange_1}
                                      value={selectedCareer_1}
                                      name='career_s1'
                                  >
                                  <option disabled value="">職務を選択してください</option>
                                  {careersOptions.map((option) => (
                                      <option key={option.value} value={option.label}>{option.label}</option>
                                  ))}
                                  </select>
                              </p>
                              <p>在籍年数:<input type="number" name="career_length1" placeholder="1" className="input input-bordered" /></p>

                              <p>Industry_2:
                                  <select
                                      className="select select-bordered w-full max-w-xs"
                                      onChange={handleIndustryChange_2}
                                      value={selectedIndustry_2}
                                  >
                                  <option disabled value="">産業を選択してください</option>
                                  {industriesOptions.map((option) => (
                                      <option key={option.value} value={option.value}>{option.label}</option>
                                  ))}
                                  </select>
                              </p>
                              <p>detail_2:
                                  <select
                                      className="select select-bordered w-full max-w-xs"
                                      onChange={handleDetailChange_2}
                                      value={selectedDetail_2}
                                      name='career_l2'
                                  >
                                  <option disabled value="">業務詳細を選択してください</option>
                                  {detailsOptions[selectedIndustry_2]?.map((option) => (
                                      <option key={option.value} value={option.label}>{option.label}</option>
                                  ))}
                                  </select>
                              </p>
                              <p>career_2:
                                  <select
                                      className="select select-bordered w-full max-w-xs"
                                      onChange={handleCareerChange_2}
                                      value={selectedCareer_2}
                                      name='career_s2'
                                  >
                                  <option disabled value="">職務を選択してください</option>
                                  {careersOptions.map((option) => (
                                      <option key={option.value} value={option.label}>{option.label}</option>
                                  ))}
                                  </select>
                              </p>
                              <p>在籍年数:<input type="number" name="career_length2" placeholder="1" className="input input-bordered" /></p>
                              <p>資格①:大分類
                                  <select
                                      className="select select-bordered w-full max-w-xs"
                                      onChange={handleQualificationLargeChange_1}
                                      value={selectedQualificationLarge_1}
                                  >
                                  <option disabled value="">未選択</option>
                                  {qualificationsLargeOptions.map((option) => (
                                      <option key={option.value} value={option.value}>{option.label}</option>
                                  ))}
                                  </select>
                              </p>
                              <p>資格①:小分類
                                  <select
                                      className="select select-bordered w-full max-w-xs"
                                      onChange={handleQualificationSmallChange_1}
                                      value={selectedQualificationSmall_1}
                                      name='qualification_1'
                                  >
                                  <option disabled value="">未選択</option>
                                  {qualificationsSmallOptions[selectedQualificationLarge_1]?.map((option) => (
                                      <option key={option.value} value={option.label}>{option.label}</option>
                                  ))}
                                  </select>
                              </p>
                              <p>資格②:大分類
                                  <select
                                      className="select select-bordered w-full max-w-xs"
                                      onChange={handleQualificationLargeChange_2}
                                      value={selectedQualificationLarge_2}
                                  >
                                  <option disabled value="">未選択</option>
                                  {qualificationsLargeOptions.map((option) => (
                                      <option key={option.value} value={option.value}>{option.label}</option>
                                  ))}
                                  </select>
                              </p>
                              <p>資格②:小分類
                                  <select
                                      className="select select-bordered w-full max-w-xs"
                                      onChange={handleQualificationSmallChange_2}
                                      value={selectedQualificationSmall_2}
                                      name='qualification_2'
                                  >
                                  <option disabled value="">未選択</option>
                                  {qualificationsSmallOptions[selectedQualificationLarge_2]?.map((option) => (
                                      <option key={option.value} value={option.label}>{option.label}</option>
                                  ))}
                                  </select>
                              </p>

                          </div>
                          <div className="p-5 flex items-center justify-center">
                              <button type="submit" className="btn btn-primary">
                                  選択結果確定
                              </button>
                          </div>
                    </form>
                  </div>
              </div>
            </div>
        </>
    )
}



